# Generated by Django 5.1.4 on 2025-01-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subjects',
            constraint=models.UniqueConstraint(fields=('class_assigned', 'name'), name='unique_subject_per_class'),
        ),
    ]
