# Generated by Django 5.1.4 on 2024-12-31 00:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('gender', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('address_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_of_registration', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gender.gender')),
                ('special_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.specialized')),
                ('subjects', models.ManyToManyField(to='subjects.subjects')),
            ],
        ),
    ]
