# Generated by Django 5.1.4 on 2025-01-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='username',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
