[build]
  base = "frontend"  # Point Netlify to the frontend directory
  command = "npm run build"
  publish = "frontend/build"

[functions]
  directory = "backend/netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.8.10"  # Replace with your desired Python version
  RUBY_VERSION = "2.7.2"    # Replace with your desired Ruby version
