# Generated by Django 4.2.17 on 2025-01-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateField()),
                ('profile_picture', models.ImageField(upload_to='teacher_profiles/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
