# Generated by Django 5.1.4 on 2025-01-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_registration_password'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='subjects.subjects'),
        ),
    ]
