# Generated by Django 5.1.4 on 2025-01-04 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gender.gender'),
        ),
    ]
